### ISSUE TITLE
I get this problem in VidMasta

### ISSUE THREAD

**Issue by popcorn2024ok** [ALGwares/VidMasta#1]
<img width="622" alt="Captura de pantalla 2024-07-29 a la(s) 1 02 07 p  m" src="https://github.com/user-attachments/assets/b4362550-e793-40e6-b068-b03e4134b5e1">

When I want to play something I get this problem and error. Can it be solved soon? I downloaded it on my Mac

The download link could not be found

**Comment by ALGwares** [comment]
I have manually confirmed that the download for Rugrats Shorts 2021 is not available from the video sources that VidMasta searches.
